### ISSUE TITLE
Generate top-level navigation

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-boilerplate-net#10]
We'd like to have a functionality that would generate top-level navigation based on sitemap data in Kentico Cloud.

https://kenticocloud.com/blog/managing-navigation-menus-in-kentico-cloud

Similarly to https://github.com/Kentico/cloud-boilerplate-net/issues/3, the issue is blocked by the capabilities of the [sitemap](https://developer.kenticocloud.com/v1.0/reference#list-sitemap-locations) endpoint.

**Comment by JanLenoch** [comment]
There are other plans with the Sitemap feature.
