### ISSUE TITLE
Allow storing the Preview API key without being actually used in requests

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-boilerplate-net#19]
When the CloudBoilerplateNet.ProjectOptions.KenticoCloudPreviewApiKey property is set, then all requests to the REST endpoints are being done with the Preview API key. The app should allow the developer to configure the Preview API key without forcing the app to actually use it.

**Comment by petrsvihlik** [comment]
I suggest we go back to the DeliveryClientFactory then. We inject it to the controller and let it decide what implementation of `IDeliveryClient` will it return. The sample implementation can be based on query string (e.g. if ?preview=1). 

Also, we shouldn't cache preview responses at all. So it should return the basic implementation from the SDK, I guess.

**Comment by petrsvihlik** [comment]
Let's wait until we figure out what's the best practice.

**Comment by petrsvihlik** [comment]
It's possible with the [`DeliveryOptions.UsePreviewApi`](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/Configuration/DeliveryOptions%20.cs) now.

**Comment by JanLenoch** [comment]
It would be great to set the UsePreviewApi with the help of [IOptions](https://docs.microsoft.com/aspnet/core/api/microsoft.extensions.options.ioptions-1).

**Comment by petrsvihlik** [comment]
Basically, we goal of this task is to use DI to configure the `DeliveryClient` as described [here](https://github.com/Kentico/delivery-sdk-net/wiki/Using-the-ASP.NET-Core-Configuration-API-and-DI-to-Instantiate-the-DeliveryClient)

**Comment by petrsvihlik** [comment]
will be solved by #39
