### ISSUE TITLE
Generate sitemap.xml from Kentico Cloud Delivery endpoint

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/cloud-boilerplate-net#3]
Once `/sitemap` delivery endpoint is available, we can start generating sitemap.xml automatically.

**Comment by petrsvihlik** [comment]
We need a reliable way to get url_slugs or complete relative paths of sitemap locations to be able to generate URLs of content items.

**Comment by JanLenoch** [comment]
There are other plans with the Sitemap feature.
