### ISSUE TITLE
Caching with Kentico Cloud

### ISSUE THREAD

**Issue by matodanko** [Kentico/cloud-boilerplate-net#33]
Simple fixed-time caching - Could you please provide more details about this functionality?
How it works, when people should use it/should not, what's the best practice for caching in general.

**Comment by JanLenoch** [comment]
Thanks @matodanko ! I'm not sure if we'll make it in time, given that the web hooks functionality might be on the way. I'll discuss it with @petrsvihlik to see what we can do.

**Comment by petrsvihlik** [comment]
@JanLenoch please extend [this paragraph](https://github.com/Kentico/cloud-boilerplate-net#how-to-set-up-fixed-time-caching) with a few sentences about how it works inside (what does it do).
