### ISSUE TITLE
Implement DeliveryOptions

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-boilerplate-net#39]
Use [DeliveryOptions](https://github.com/Kentico/delivery-sdk-net/blob/8edf2cfa032f6ecc59364900c8be0eedd06e8b6e/KenticoCloud.Delivery/Configuration/DeliveryOptions%20.cs) that's available in Delivery SDK. It can be used together with [IOptions](https://docs.microsoft.com/aspnet/core/api/microsoft.extensions.options.ioptions-1) to quickly load environment variables.

Docu: https://github.com/Kentico/delivery-sdk-net/wiki/Using-the-ASP.NET-Core-Configuration-API-and-DI-to-Instantiate-the-DeliveryClient

This will also resolve #19

**Comment by charithsoori** [comment]
I would like to work on this task.

**Comment by petrsvihlik** [comment]
great, i'll assign the issue to you once you accept the invitation to the project :)
