### ISSUE TITLE
Add full support for IISUrlRewrite.xml file format

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/cloud-boilerplate-net#4]
So far it's not fully implemented in asp.net core 1.1, but it's implemented in asp.net core 1.2 that should be released in Q2/2017 ([source](https://github.com/aspnet/BasicMiddleware/pull/168#issuecomment-286325878)). Once released, we should update boilerplate and add support for fully implemented support for `IISUrlRewrite.xml` file format. 

It will allow our users to use rewrite maps (i.g.: static redirects - old url -> new url). 

```xml
<rewrite>
  <rewriteMaps>
    <!-- TODO: not supported yet, waiting for asp.net core 1.2 release -->
    <!-- Example of 301 - Permanent redirect with old -> new URL mapping -->
    <rewriteMap name="Static rewrites" defaultValue="">
      <add key="/old-url" value="/?new-url=1" />
    </rewriteMap>
  </rewriteMaps>
</rewrite>
```

Currently, they have to use workaround or own solution.

**Comment by JanLenoch** [comment]
The next release is 2.0 (not 1.2), slated for Q3, sadly.

**Comment by petrsvihlik** [comment]
Yeah..they changed the [roadmap](https://github.com/aspnet/Home/wiki/Roadmap) :(

**Comment by JanLenoch** [comment]
The redirect/rewrite functionality is now supported directly by extension methods of the [rewrite middleware](https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/url-rewriting/sample/).
