### ISSUE TITLE
WebHook boilerplate code

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-boilerplate-net#40]
- introduce standard models for [webhook body](https://developer.kenticocloud.com/reference#webhooks-and-notifications)
- add [webhook signature verification](https://developer.kenticocloud.com/reference#webhooks-notification-signing)

**Comment by JanLenoch** [comment]
The webhook model can be copied from https://github.com/Kentico/cloud-example-webhook-cache-invalidation/blob/master/WebhookCacheInvalidationMvc/Models/KenticoCloudWebhookModel.cs .

The webhook signature verification can be copied from https://github.com/Kentico/cloud-example-webhook-cache-invalidation/blob/master/WebhookCacheInvalidationMvc/Filters/KenticoCloudSignatureActionFilter.cs .

**Comment by charithsoori** [comment]
Can I work on this Task ?

**Comment by JanLenoch** [comment]
Hi Charith, sure, you can go ahead. Just please note there is one todo: The cached content items should also be invalidated everytime their underlying content type changes (in KC). This is something that I haven't implemented in my example.

**Comment by JanLenoch** [comment]
WIP'ed in https://github.com/Kentico/cloud-boilerplate-net/tree/webhook-cache-invalidation

**Comment by JanLenoch** [comment]
Implemented via #54
