### ISSUE TITLE
Migrate to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-boilerplate-net#48]
- [x] compare with the standard ASP.NET Core 2.0 template to see if there are any new patterns that we should embrace
- [x] migrate the code

**Comment by Domitnator** [comment]
I just created a pull request for this one: #50 

The changes i did work perfectly on Microsoft Azure and Azure CI.

**Comment by petrsvihlik** [comment]
@JanLenoch can you please release a new nuget package and close this task? make sure all template configuration files are up to date and that you follow semver. thx

**Comment by JanLenoch** [comment]
Implemented via #50 .
