### ISSUE TITLE
Should we use a generic cache manager?

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-boilerplate-net#52]
There are several cache manager libraries in the wild. One of the nice ones is https://github.com/MichaCo/CacheManager . It supports various caching technologies (incl. distributed ones) and is designed to store various types of data in the cache (not only Kentico Cloud data).

Would you welcome such a generic cache manager in our boilerplate?

Pros:
* support for multiple caching technologies
* state-of-the-art caching patterns implemented (failover mechanisms, geo-replication, etc.)
* optimized for performance

Cons:
* lack of support for cache item dependencies
* lack of support for type dependencies (eg. if one content item is cached twice as both strongly-typed object and an object of type "dynamic", then both should be invalidated at the same time)

Pros and cons (at the same time):
* designed for generic usage (not with Kentico Cloud data in mind)

**Comment by petrsvihlik** [comment]
@JanLenoch can we close this? now that you implemented https://github.com/Kentico/cloud-boilerplate-net/pull/54

**Comment by JanLenoch** [comment]
This question is still quite valid because while we've addressed all the "cons", we e.g. still don't support multiple engines.

**Comment by petrsvihlik** [comment]
could you then please groom this issue?

**Comment by JanLenoch** [comment]
Sure, as part of my current grooming activity (only SDK is done ATM).

**Comment by JanLenoch** [comment]
Rewritten to #65
