### ISSUE TITLE
Article's <img> tag is generated with </img> closing even it is a void element

### ISSUE THREAD

**Issue by mcetkovsky** [Kentico/cloud-boilerplate-net#57]
The `HtmlHelperExtensions.AssetImage` method builds an `img` tag which than renders as

`<img …></img>`

The `img` tag is a [void element](https://www.w3.org/TR/html5/syntax.html#void-elements). So it should be rendered as just `<img>` (HTML5, HTML) or self-closed `<img/>` (HTML5, XHTML).

I suggest to add one of the following lines just before the `return image;` statement to fix this.

`image.TagRenderMode = TagRenderMode.SelfClosing; // XHTML-like <img/>`

`image.TagRenderMode = TagRenderMode.StartTag; // HTML-like <img>`

**Comment by petrsvihlik** [comment]
I'd go with `SelfClosing`

**Comment by Simply007** [comment]
As you have mentioned:
>  Void elements only have a start tag; end tags must not be specified for void elements.  

I would also vote for self-enclosing since Images on the sample MVC image widget for EMS also use a self-closing tag.

Are you able to submit a pull request? @mcetkovsky

**Comment by mcetkovsky** [comment]
> Are you able to submit a pull request?

Fully busy now, hopefully in a month or so.
