### ISSUE TITLE
Updating Boilerplate found a new issue, possibly?

### ISSUE THREAD

**Issue by mcbeev** [Kentico/cloud-boilerplate-net#58]
In an early release of the boilerplate I could use the CachedDeliveryClient's `GetItemAsync` method without any parameters:

`var response = await DeliverClient.GetItemAsync<FullWidthContentPage>(PageCodeName);`

I updated to the latest release code as of yesterday, and now I receive an error on that line: "parameter cannot be null". To get around it I was able to pass in an empty List<IQueryParameter> but that was the only way I could get it to work. Like so:

`var response = await DeliverClient.GetItemAsync<FullWidthContentPage>(PageCodeName, new List<IQueryParameter>());`

I believe the issue is in how the code is written in `KenticoCloudCacheHelper.cs` for the `GetIdentifiersFromParameters` method, but I am not 100%.

I'm hoping someone can validate my findings, or tell me if I am wrong?

**Comment by Simply007** [comment]
@JanLenoch do you have information about this change you did in the following commit?
https://github.com/Kentico/cloud-boilerplate-net/commit/23c78ac85d6d01df8c807835f9699e111843ac79#diff-e1ac2c647007aa447031861b0a9d79c0L118

**Comment by JanLenoch** [comment]
I can reproduce that behavior, but I'll need to understand why such an exception happens when there's a default parameter value in the DeliveryClient.GetItemAsync<T> method (in the SDK).

Thanks @mcbeev for reporting it! I'll take a look at it.

**Comment by mcbeev** [comment]
Thanks Jan and Ondra, Ill update my project this weekend with the changes.

**Comment by mcbeev** [comment]
Thanks for the quick patch gentlemen. Every works without passing any params again. Hurray!
