### ISSUE TITLE
Rewrite CachedDeliveryClient so that it follows the decorator pattern

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-boilerplate-net#63]
### Motivation

Currently, the [CachedDeliveryClient](https://github.com/Kentico/cloud-boilerplate-net/blob/master/src/content/CloudBoilerplateNet/Services/CachedDeliveryClient.cs) references `protected DeliveryClient DeliveryClient { get; }` [which](https://github.com/Kentico/cloud-boilerplate-net/blob/master/src/content/CloudBoilerplateNet/Services/CachedDeliveryClient.cs#L21) is wrong. It should reference `IDeliveryClient`.

### Design guidelines

- CachedDeliveryClient should accept `IDeliveryClient` in the constructor
- The current constructor should be removed/altered
- Instances of `DeliveryClient` should be created outside the `CachedDeliveryClient`
- `public HttpClient HttpClient` will no longer be necessary in the `CachedDeliveryClient`
    - tests will create fake `HttpClient` and pass it to an instance of the `DeliveryClient` which will be passed to `CachedDeliveryClient` 

### Reference

* https://www.dofactory.com/net/decorator-design-pattern

**Comment by amoraitis** [comment]
I could work on it @petrsvihlik

**Comment by petrsvihlik** [comment]
awesome @amoraitis . I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

**Comment by amoraitis** [comment]
> awesome @amoraitis . I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

Done✔
