### ISSUE TITLE
Update the template to ASP.NET Core 2.1

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-boilerplate-net#64]
### Motivation

In spite of being just a dot release, the 2.1 brings [many updates](https://msdn.microsoft.com/magazine/mt829706?MC=WebDev&MC=ASPNET&MC=Vstudio&MC=JavaScript&MC=MobileDev) and [performance improvements](https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1/).

### Design guidelines

Upgrade according to references below. Rewrite code that's deprecated by MS.

### Reference

* https://docs.microsoft.com/en-us/aspnet/core/migration/20_21
* https://www.stevejgordon.co.uk/upgrading-aspnet-core-2-application-aspnet-core-2-1-preview-1
* https://elanderson.net/2018/06/migration-from-asp-net-core-2-0-to-2-1/
* https://www.c-sharpcorner.com/article/how-to-update-net-core-2-0-application-to-2-1-version/

**Comment by Sprot** [comment]
I'l have a go
